# Taps
tap 'cloudflare/cloudflare'
tap 'heroku/brew'
tap 'loopwork-ai/tap'
tap 'planetscale/tap'
tap 'thoughtbot/formulae' # for `pick` binary
tap 'anomalyco/tap'
tap 'travisvn/tap'

# Binaries
brew 'autojump'
brew 'cloudflared'
brew 'cog'
brew 'exiftool'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'go'
brew 'imagemagick'
brew 'magic-wormhole'
brew 'node'
brew 'pnpm'
brew 'opencode'
brew 'pick'
brew 'pscale'
brew 'pure'
brew 'rclone'
brew 'ripgrep'
brew 'slackdump'
brew 'tesseract'
brew 'tree'
brew 'wget'
brew 'yq'
brew 'yt-dlp'
brew 'uv'

# Spatie Medialibrary
# brew 'jpegoptim'
# brew 'optipng'
# brew 'pngquant'
# brew 'svgo'
# brew 'gifsicle'

# Apps
cask 'arc'
cask 'audacity'
cask 'autodesk-fusion'
cask 'caffeine'
cask 'chatgpt'
cask 'claude'
cask 'cleanshot'
cask 'cursor'
cask 'discord'
cask 'figma'
cask 'firefox'
cask 'gather'
cask 'ghostty'
cask 'github'
cask 'keycastr'
cask 'linear-linear'
cask 'lm-studio'
cask 'loom'
cask 'maccy'
cask 'mousepose'
cask 'ngrok'
cask 'notion'
cask 'opencode-desktop'
cask 'obs'
cask 'rectangle'
cask 'orbstack'
cask 'plex-media-server'
cask 'raycast'
cask 'screen-studio'
cask 'shotcut'
cask 'signal'
cask 'simplenote'
cask 'sketch'
cask 'slack'
cask 'spotify'
cask 'superwhisper'
cask 'telegram'
cask 'thunderbird'
cask 'visual-studio-code'
cask 'vlc'
cask 'warp'
cask 'webtorrent'
cask 'whatsapp'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'